// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHcATMYdZ9mxgXMl_y12GptIf9lmU0dMM',
    appId: '1:1041483119113:web:e490227d190f4303fa56d8',
    messagingSenderId: '1041483119113',
    projectId: 'talpamigosecreto',
    authDomain: 'talpamigosecreto.firebaseapp.com',
    storageBucket: 'talpamigosecreto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6i0slC_MBNYV9nd1V0hEfc1Dm8QY5g_w',
    appId: '1:1041483119113:android:0926bb9a6d9272dffa56d8',
    messagingSenderId: '1041483119113',
    projectId: 'talpamigosecreto',
    storageBucket: 'talpamigosecreto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJFPTLM5REV5pkNfJ5_BipOXVOhbSODLE',
    appId: '1:1041483119113:ios:c144fcc631295a1efa56d8',
    messagingSenderId: '1041483119113',
    projectId: 'talpamigosecreto',
    storageBucket: 'talpamigosecreto.firebasestorage.app',
    iosBundleId: 'com.example.amigoSecretoTalp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJFPTLM5REV5pkNfJ5_BipOXVOhbSODLE',
    appId: '1:1041483119113:ios:c144fcc631295a1efa56d8',
    messagingSenderId: '1041483119113',
    projectId: 'talpamigosecreto',
    storageBucket: 'talpamigosecreto.firebasestorage.app',
    iosBundleId: 'com.example.amigoSecretoTalp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHcATMYdZ9mxgXMl_y12GptIf9lmU0dMM',
    appId: '1:1041483119113:web:2bffaddcb7e09517fa56d8',
    messagingSenderId: '1041483119113',
    projectId: 'talpamigosecreto',
    authDomain: 'talpamigosecreto.firebaseapp.com',
    storageBucket: 'talpamigosecreto.firebasestorage.app',
  );
}
