// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI0r84iNodkgL65GIATiIPEUG_9U7ryF0',
    appId: '1:928335276212:web:dc8d5720a03b45976d0fe1',
    messagingSenderId: '928335276212',
    projectId: 'feed-project-963bb',
    authDomain: 'feed-project-963bb.firebaseapp.com',
    storageBucket: 'feed-project-963bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCiKprQUppZjJRW9Luuh19UyqXoeftCrQ',
    appId: '1:928335276212:android:985125bd847b514d6d0fe1',
    messagingSenderId: '928335276212',
    projectId: 'feed-project-963bb',
    storageBucket: 'feed-project-963bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW_kxIP_6e0WS1ZXARqPJOElyuxLYYwls',
    appId: '1:928335276212:ios:3edc2e60f57d73376d0fe1',
    messagingSenderId: '928335276212',
    projectId: 'feed-project-963bb',
    storageBucket: 'feed-project-963bb.firebasestorage.app',
    iosBundleId: 'com.example.amigoSecretoTalp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW_kxIP_6e0WS1ZXARqPJOElyuxLYYwls',
    appId: '1:928335276212:ios:3edc2e60f57d73376d0fe1',
    messagingSenderId: '928335276212',
    projectId: 'feed-project-963bb',
    storageBucket: 'feed-project-963bb.firebasestorage.app',
    iosBundleId: 'com.example.amigoSecretoTalp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI0r84iNodkgL65GIATiIPEUG_9U7ryF0',
    appId: '1:928335276212:web:ff8f6447269bc3bd6d0fe1',
    messagingSenderId: '928335276212',
    projectId: 'feed-project-963bb',
    authDomain: 'feed-project-963bb.firebaseapp.com',
    storageBucket: 'feed-project-963bb.firebasestorage.app',
  );
}
